version: '3.5'
services:
  fraud_check:
    build: .
    image: fraud_check
    restart: "always"
    command: "python app.py"
    ports:
      - "5000:5000"
    volumes:
      - ./:/code
    network_mode: host
